### ISSUE TITLE
Cannot locate rosdep definition for [nav_pcontroller]

### ISSUE THREAD

**Issue by xMutzelx** [cram2/cram_pr2#2]
Hello,
I try to install CRAM with this tutorial: http://cram-system.org/installation
At the moment I try to use this command: rosdep install --ignore-src --from-paths src/ but I get the following error:
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
cram_pr2_low_level: Cannot locate rosdep definition for [nav_pcontroller]
I am using Ubuntu 14.04 and Ros Indigo. Every step before worked without errors or warning.
Thank you for your help.

**Comment by gaya-** [comment]
Hi,

Sorry, my bad, should be fixed now (in d71de638d2d6f2a6a5272f4e208607150f6df4e5).
Try to `git pull` on `cram_pr2` and then `rosdep install` again.

Thanks for the report.
